/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocLeadIdRouteImport } from './routes/doc.$leadId'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as LeadsImportRouteImport } from './routes/leads.import'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as MarketingBrandRouteImport } from './routes/marketing.brand'
import { Route as MarketingCardsRouteImport } from './routes/marketing.cards'
import { Route as PitchLeadIdRouteImport } from './routes/pitch.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocLeadIdRoute = DocLeadIdRouteImport.update({
  id: '/doc/$leadId',
  path: '/doc/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsImportRoute = LeadsImportRouteImport.update({
  id: '/leads/import',
  path: '/leads/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingBrandRoute = MarketingBrandRouteImport.update({
  id: '/marketing/brand',
  path: '/marketing/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCardsRoute = MarketingCardsRouteImport.update({
  id: '/marketing/cards',
  path: '/marketing/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchLeadIdRoute = PitchLeadIdRouteImport.update({
  id: '/pitch/$leadId',
  path: '/pitch/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/doc/$leadId': typeof DocLeadIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/import': typeof LeadsImportRoute
  '/leads/new': typeof LeadsNewRoute
  '/marketing/brand': typeof MarketingBrandRoute
  '/marketing/cards': typeof MarketingCardsRoute
  '/pitch/$leadId': typeof PitchLeadIdRoute
  '/marketing/': typeof MarketingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/doc/$leadId': typeof DocLeadIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/import': typeof LeadsImportRoute
  '/leads/new': typeof LeadsNewRoute
  '/marketing/brand': typeof MarketingBrandRoute
  '/marketing/cards': typeof MarketingCardsRoute
  '/pitch/$leadId': typeof PitchLeadIdRoute
  '/marketing': typeof MarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/doc/$leadId': typeof DocLeadIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/import': typeof LeadsImportRoute
  '/leads/new': typeof LeadsNewRoute
  '/marketing/brand': typeof MarketingBrandRoute
  '/marketing/cards': typeof MarketingCardsRoute
  '/pitch/$leadId': typeof PitchLeadIdRoute
  '/marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/doc/$leadId'
    | '/leads/$leadId'
    | '/leads/import'
    | '/leads/new'
    | '/marketing/brand'
    | '/marketing/cards'
    | '/pitch/$leadId'
    | '/marketing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/doc/$leadId'
    | '/leads/$leadId'
    | '/leads/import'
    | '/leads/new'
    | '/marketing/brand'
    | '/marketing/cards'
    | '/pitch/$leadId'
    | '/marketing'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/doc/$leadId'
    | '/leads/$leadId'
    | '/leads/import'
    | '/leads/new'
    | '/marketing/brand'
    | '/marketing/cards'
    | '/pitch/$leadId'
    | '/marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DocLeadIdRoute: typeof DocLeadIdRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsImportRoute: typeof LeadsImportRoute
  LeadsNewRoute: typeof LeadsNewRoute
  MarketingBrandRoute: typeof MarketingBrandRoute
  MarketingCardsRoute: typeof MarketingCardsRoute
  PitchLeadIdRoute: typeof PitchLeadIdRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$leadId': {
      id: '/doc/$leadId'
      path: '/doc/$leadId'
      fullPath: '/doc/$leadId'
      preLoaderRoute: typeof DocLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/import': {
      id: '/leads/import'
      path: '/leads/import'
      fullPath: '/leads/import'
      preLoaderRoute: typeof LeadsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/brand': {
      id: '/marketing/brand'
      path: '/marketing/brand'
      fullPath: '/marketing/brand'
      preLoaderRoute: typeof MarketingBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/cards': {
      id: '/marketing/cards'
      path: '/marketing/cards'
      fullPath: '/marketing/cards'
      preLoaderRoute: typeof MarketingCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch/$leadId': {
      id: '/pitch/$leadId'
      path: '/pitch/$leadId'
      fullPath: '/pitch/$leadId'
      preLoaderRoute: typeof PitchLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DocLeadIdRoute: DocLeadIdRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsImportRoute: LeadsImportRoute,
  LeadsNewRoute: LeadsNewRoute,
  MarketingBrandRoute: MarketingBrandRoute,
  MarketingCardsRoute: MarketingCardsRoute,
  PitchLeadIdRoute: PitchLeadIdRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
