/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocLeadIdRouteImport } from './routes/doc.$leadId'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as LeadsNewRouteImport } from './routes/leads.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocLeadIdRoute = DocLeadIdRouteImport.update({
  id: '/doc/$leadId',
  path: '/doc/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/doc/$leadId': typeof DocLeadIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/doc/$leadId': typeof DocLeadIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/doc/$leadId': typeof DocLeadIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/doc/$leadId' | '/leads/$leadId' | '/leads/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/doc/$leadId' | '/leads/$leadId' | '/leads/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/doc/$leadId'
    | '/leads/$leadId'
    | '/leads/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DocLeadIdRoute: typeof DocLeadIdRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsNewRoute: typeof LeadsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$leadId': {
      id: '/doc/$leadId'
      path: '/doc/$leadId'
      fullPath: '/doc/$leadId'
      preLoaderRoute: typeof DocLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DocLeadIdRoute: DocLeadIdRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsNewRoute: LeadsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
